name: Build Docker Image

on:
  workflow_call:
    inputs:
      image-tag:
        type: string
        required: true
        default: sistema-riego:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t ${{ inputs.image-tag }} .
