name: Deploy from Git

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout del código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar Git con nombre y correo
      - name: Configure Git
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your-email@example.com"

      # Realizar cambios o acciones necesarias (opcional)
      - name: Make changes (optional)
        run: |
          echo "Optional changes made" >> changes.txt
          git add .
          git commit -m "Optional changes"

      # Empujar los cambios al repositorio remoto
      - name: Push changes to Git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main
