name: Main CI/CD Pipeline for SISTEMA DE RIEGO

on:
  push:
    branches:
      - main # Rama que activa el workflow automáticamente
  pull_request: # Opcional: activa el workflow en solicitudes de extracción
    branches:
      - main
  workflow_dispatch: # Permite ejecutar el workflow manualmente desde GitHub Actions

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write
  actions: read
  security-events: write
  packages: write

jobs:
  build:
    name: Build Docker Image
    uses: ./.github/workflows/build-docker.yml
    secrets: inherit

  dast-scan:
    name: DAST Scan
    needs: build
    uses: ./.github/workflows/dast-scan.yml
    secrets: inherit

  deploy:
    name: Deploy to Vercel
    needs: dast-scan
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
