name: CI/CD Pipeline with DAST, CodeQL, and Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  checks: write
  pull-requests: write
  actions: read
  security-events: write
  packages: write

jobs:
  build:
    name: Build Docker Image
    uses: ./.github/workflows/build-docker.yml
    secrets: inherit
    with:
      image-tag: "sistema-riego:latest"

  codeql:
    name: CodeQL Analysis
    needs: build
    uses: ./.github/workflows/sca-codeql.yml
    secrets: inherit
    with:
      branch: main

  dast-scan:
    name: DAST Scan
    needs: codeql
    uses: ./.github/workflows/dast-scan.yml
    secrets: inherit
    with:
      image-tag: sistema-riego:latest

  deploy:
    name: Deploy to Vercel
    needs: dast-scan
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
