name: Main CI/CD SISTEMA DE RIEGO

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write
  actions: read
  security-events: write
  packages: write

jobs:
  build:
    name: Build Docker Image
    uses: ./.github/workflows/build-docker.yml
    secrets: inherit
    with:
      image-tag: "sistema-riego:latest"

  dast-scan:
    name: DAST Scan
    needs: build
    uses: ./.github/workflows/dast-scan.yml
    secrets: inherit
    with:
      image-tag: "sistema-riego:latest"

  deploy:
    name: Deploy to Vercel
    needs: dast-scan
    uses: ./.github/workflows/deploy-to-vercel.yml
    secrets: inherit
